### ISSUE TITLE
Orden iconos en queries "Últimas Estadísticas", "Últimas...", etc.

### ISSUE THREAD

**Issue by uncoded** [uncoded/cores#1]
Definir orden iconos para archivos (pdf, excel) en secciones Estadísticas, Publicaciones, etc. Independientemente del orden que se hayan subido los archivos, el PDF siempre ha de mostrarse antes que el EXCEL.

**Comment by juanpablocruz** [comment]
Arreglado!.

En cada tpl he tenido que añadir un array lista_archivos,
en el switch añado los archivos a ese array...si es pdf lo añado al principio con array_unshift y sino array_push.
Luego recorro el array añadiendo esos archivos al string ficheros.
