### ISSUE TITLE
Calendario de publicaciones no muestra publicaciones sin PDF

### ISSUE THREAD

**Issue by uncoded** [uncoded/cores#3]
Si se publica algo con toda la info (incluido archivo PDF), la Rule se ejecuta correctamente y se guarda la info en tabla_eventos. Si no hay PDF, no se guarda la info. Esto es muy necesario ya que hemos de tener la posibilidad de anunciar las publicaciones (sin info, sólo título) para que más adelante se puedan actualizar en fecha en el calendario.

**Comment by juanpablocruz** [comment]
Arreglado.

He cambiado que la tabla que se seleccione sea nodo y sea esa la que se una al resto, luego he cambiado en el insert y update $record->entity por $node->nid ya que deberian coincidir pero en caso de no dar resultados fallaba.

Ademas he añadido una comprobación de que $record->archivo != NULL para todo el bucle interno.
