### ISSUE TITLE
Cambiar query "Últimas publicaciones"

### ISSUE THREAD

**Issue by uncoded** [uncoded/cores#4]
La info de las fechas se intercambia. La columna de Fecha de referencia sería Fecha de publicación y la info de Año y mes se recuperaría del campo de Fecha de referencia. Quedaría de la siguiente manera:

Ahora:
![antes](https://f.cloud.github.com/assets/6526986/2043764/8b7df4ce-89e2-11e3-9ae1-40963dde9af8.png)
Después:
![despues](https://f.cloud.github.com/assets/6526986/2043767/9038babc-89e2-11e3-8d1d-561dcbb75d03.png)

**Comment by uncoded** [comment]
Sería necesario hacer lo mismo también en la query de i_Cores

**Comment by juanpablocruz** [comment]
Hecho!
